### ISSUE TITLE
File is stuck at overwrite

### ISSUE THREAD

**Issue by starfoxe** [lucataco/cog-InterpAny-Clearer#1]
New files are not being passed through because the ffmpeg is stuck on this video handler overwrite. add -y to the ffmpeg command to overwrite previous files.  @lucataco 

<img width="613" alt="Screen Shot 2023-11-29 at 10 56 01 AM" src="https://github.com/lucataco/cog-InterpAny-Clearer/assets/150199206/16f748a3-6956-46d8-8af6-cb485112c504">

**Comment by lucataco** [comment]
Thanks for the find! Fixed
